export const CONFIG_KEYS = {
  IMAGE_STORAGE_PATH: 'image.storagePath',
  MAX_DISPLAY_SIDE: 'max.display.side',
  PROXY_CHECK_TIMEOUT: 'proxy.check.timeout',
  PROXY_CHECK_API_KEY: 'proxy.check.apiKey',
  PROXY_CHECK_PROVIDER_TYPE: 'proxy.check.providerType',
  SCREENSHOT_STORAGE_PATH: 'screenshot.storagePath',
  VIDEO_CODEC_PREFERENCE: 'video.codec.preference',
  RENDER_PREFERENCE: 'render.preference',
  DISABLE_HARDWARE_ACCELERATION: 'disable.hardware.acceleration',
  MAIN_WINDOW_SIZE: 'main.window.size',
  WHEEL_SPEED: 'wheel.speed',
  KEEP_HOVER_MOVE: 'keep.hover.move',
  MINIMIZE_TO_TRAY: 'minimize.to.tray',
  APP_LANGUAGE: 'app.language',
  CLIENT_UPDATE_CACHE: 'client.update.cache',
  CLIENT_UPDATE_IGNORED_VERSION: 'client.update.ignored.version',
  IS_STREAMING: 'is.streaming',
  THEME_MODE: 'theme.mode',
  THEME_COLOR: 'theme.color',
  STREAM_FPS: 'stream.fps',
  STREAM_BITRATE: 'stream.bitrate'
} as const
