export const IMAGES_EVENTS = {
  // 更改存储路径
  CHANGE_STORAGE_PATH: 'IMAGES:CHANGE_STORAGE_PATH',
  // 获取所有镜像
  GET_IMAGES: 'IMAGES:GET_IMAGES',
  // 查询镜像
  QUERY_IMAGES: 'IMAGES:QUERY_IMAGES',
  // 根据ID获取镜像
  GET_IMAGE_BY_ID: 'IMAGES:GET_IMAGE_BY_ID',
  // 添加镜像
  ADD_IMAGE: 'IMAGES:ADD_IMAGE',
  // 删除镜像
  DELETE_IMAGE: 'IMAGES:DELETE_IMAGE',
  // 批量删除镜像
  DELETE_IMAGES: 'IMAGES:DELETE_IMAGES',

  // 上传镜像
  UPLOAD_IMAGE: 'IMAGES:UPLOAD_IMAGE',
  // 解压镜像进度
  IMAGE_EXTRACT_PROGRESS: 'IMAGES:IMAGE_EXTRACT_PROGRESS',

  // 上传镜像到主机
  UPLOAD_IMAGE_TO_HOST: 'IMAGES:UPLOAD_IMAGE_TO_HOST',

  // 上传镜像到主机进度
  UPLOAD_IMAGE_TO_HOST_PROGRESS: 'IMAGES:UPLOAD_IMAGE_TO_HOST_PROGRESS',

  // 检测镜像存储路径是否存在
  CHECK_STORAGE_PATH: 'IMAGES:CHECK_STORAGE_PATH'
}
